name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  get_it: ^8.0.3
  supabase_flutter: ^2.9.1
  fpdart: ^1.1.1
  internet_connection_checker_plus: ^2.7.0
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  numberpicker: ^2.1.2
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  dotted_border: ^2.1.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logos/app-logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/config/
    - assets/images/
    - assets/images/lottie/
    - assets/images/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf